### ISSUE TITLE
Add second Basic Android Project

### ISSUE THREAD

**Issue by sunkusaarthak** [sunkusaarthak/Basic-Android-Projects#3]
Add project in a new Folder by creating a folder with the project name.

**Comment by Samarthasbhat** [comment]
I will solve this issue please assign me @sunkusaarthak

**Comment by Samarthasbhat** [comment]
I have done a project own the screenshot is present in my github repo you can see it  https://github.com/Samarthasbhat/Thought
@sunkusaarthak

**Comment by sunkusaarthak** [comment]
assigned!

**Comment by Samarthasbhat** [comment]
I have added the file can please merge it and added screenshot named as s1 s2 etc @sunkusaarthak

**Comment by Samarthasbhat** [comment]
The issue has been solved

**Comment by sunkusaarthak** [comment]
Hay can you please resolve the review #5
